apiVersion: v1
kind: Pod
metadata:
  name: model-store-pod
spec:
  volumes:
    - name: model-store
      persistentVolumeClaim:
        claimName: onnx-cifar10-pvc
  containers:
    - name: model-store
      image: ubuntu
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - mountPath: "/models"
          name: model-store
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
