build:
	docker build -t kairos9603/kserve-titon-transfomer:latest .

push:
	docker push kairos9603/kserve-titon-transfomer:latest

run:
	docker run --platform amd64 -it kairos9603/kserve-titon-transfomer